### ISSUE TITLE
Invalid SSL Certifiate

### ISSUE THREAD

**Issue by yuanzhou** [bd2kccd/ccd-web#2]
I went to https://dxcvm26.psc.edu/ccd by following the README, and got the SSL error in both Google Chrome and Firefox.

![capture](https://cloud.githubusercontent.com/assets/195873/11629035/986ffe2a-9cc3-11e5-8eee-178b1c09ed36.PNG)

![capture2](https://cloud.githubusercontent.com/assets/195873/11628997/6753d690-9cc3-11e5-8a77-bfac7ad7293e.PNG)

Then I tested the plain http at http://dxcvm26.psc.edu/ccd and it worked.

**Comment by espinoj** [comment]
New ssl certificate has been installed but it looks like intermediate certificates still need to be installed.

**Comment by yuanzhou** [comment]
issue addressed.
