### ISSUE TITLE
File upload error with file file data_%20.txt

### ISSUE THREAD

**Issue by yuanzhou** [bd2kccd/ccd-web#30]
I tried to upload a file named "data_%20.txt" and it was uploaded, and then I summarized this data file. But when I clicked the link of this file name to view more info, it says nothing.

![capture](https://cloud.githubusercontent.com/assets/195873/20014416/3f08fe4c-a28d-11e6-8c49-b98ad6ba3f54.PNG)
![capture22](https://cloud.githubusercontent.com/assets/195873/20014417/40624ab4-a28d-11e6-9811-1a766341f932.PNG)

I'm guessing it has something to do with the file name.

**Comment by kvb2univpitt** [comment]
Fixed!  Good catch!
