### ISSUE TITLE
Time out error in large datasets

### ISSUE THREAD

**Issue by ccd-helpdesk** [bd2kccd/ccd-web#43]
Hi,

This came up in the ccd-helpdesk:

"I can successfully upload my datasets, specify constraints (prior knowledge), and it seems to work out for smaller datasets. But, for some larger datasets (I have ones with 1,054 and 1,212 columns), I keep getting a timeout error message after one hour from launching each job"

This is the error the user gets:

SLURM Job_id=662001 Name=causal-cmd ccd2 charmgil Failed, Run time 01:00:01, TIMEOUT

Any ideas ?

**Comment by ccd-helpdesk** [comment]
Hi, Ruben from the ccd-helpdesk here,

Any ideas behind the error the user reported in the above post.

Thanks

**Comment by espinoj** [comment]
If we could get a copy of the dataset to replicate we would be able to see what is going on.  With just a time out error it could be - error because of memory, error because of parsing bad data, error in the program itself...

- jeremy

**Comment by ccd-helpdesk** [comment]
Jeremy,

I attached the datasets that the user has been having problems with. 
This is the user's email, explaining the datasets:

" I am attaching the data files that I tried with: genbase.zip and enron.zip. Each zip file contains one .csv and one .prior file that are data and prior knowledge, respectively.
In the csv files, I give the variable names as X1, X2, ...., Y1, Y2, ..... These names simply came from the original data file where X1, X2, ... correspond to the input; Y1, Y2, ... correspond to the output.
In the prior files, I specified the edges/arcs that I do not want to have: I tried to forbid arcs between X's (between any two input variables) and arcs from Y's to X's (from output to input).
Please feel free to let me know if you need any other clarification or have any questions.


[genbase.zip](https://github.com/bd2kccd/causal-web/files/720867/genbase.zip)

[enron.zip](https://github.com/bd2kccd/causal-web/files/720866/enron.zip)
