### ISSUE TITLE
Relogin after session expired via popup modal window

### ISSUE THREAD

**Issue by yuanzhou** [bd2kccd/ccd-web#5]
Just noticed this today, when I was on the datasets section, and my computer was inactive for a while. After I came back, I clicked the file name and got a popup with the login form. I assume this is because my session was destroyed. After I typed my username and password I got logged in again but this time the web page is displaying inside that small modal window. Maybe a redirection can solve this.

![capture](https://cloud.githubusercontent.com/assets/195873/14391432/f77af20e-fd89-11e5-9460-cff675991f1f.PNG)

**Comment by kvb2univpitt** [comment]
The application cannot control this.
