### ISSUE TITLE
Causal Web not working

### ISSUE THREAD

**Issue by gl97at** [bd2kccd/ccd-web#81]
Hello,

I am trying to use the "Causal Web" program, clicking on the URL found on the CCD's site: https://cloud.ccd.pitt.edu/ccd-web. Unfortunately, I got this message: "Service Temporarily Unavailable" 
![Capture](https://user-images.githubusercontent.com/64349975/80301352-5a758f80-87ac-11ea-949c-6fd98d2146b3.JPG)

Then, as User Guide suggests, I visited another URL: https://ccd4.vm.bridges.psc.edu/ccd/, but again the site can't be reached. 

Do you have any idea about what is going on?

Thank you in advance!

**Comment by kvb2univpitt** [comment]
Hello,

The web application has been discontinued.  We no longer provide support for it.  You can use Tetrad in place of the web application:
https://github.com/cmu-phil/tetrad

Thanks.

**Comment by gl97at** [comment]
Thank you very much for your answer!
